# Generated by Django 5.2.11 on 2026-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_defence_pokemonentity_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='', verbose_name='Описание покемона'),
        ),
    ]
