# Generated by Django 5.2.11 on 2026-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(choices=[('RU', 'На русском'), ('EN', 'На английском'), ('JP', 'На японском')], max_length=200, verbose_name='Название покемона'),
        ),
    ]
