# Generated by Django 5.2.11 on 2026-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_alter_pokemon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(default='-', max_length=200, verbose_name='Название покемона на английском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default='-', max_length=200, verbose_name='Название покемона на японском'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(default='-', max_length=200, verbose_name='Название покемона на русском'),
        ),
    ]
