# Generated by Django 5.2.11 on 2026-02-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_remove_pokemon_title_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_ru',
            new_name='title',
        ),
    ]
